language: go

sudo: false

addons:
  apt:
    packages:
      - zookeeperd

go:
  - 1.7

install:
  # WORKING DIR
  # $HOME/gopath/src/github.com/QubitProducts/bamboo
  - export PATH=$PATH:$HOME/gopath/bin

  # Install build dependencies
  - go get github.com/tebeka/go2xunit
  - go get github.com/smartystreets/assertions
  - go get -t github.com/smartystreets/goconvey
  - go get -v -u github.com/tools/godep
  - go get github.com/mattn/goveralls
  - go get github.com/go-playground/overalls

# Tests should fail if go fmt is required
script:
  - godep restore
  - '[[ -z "$(go fmt ./... | tee -a /dev/stderr)" ]]'
  - go vet ./...
  - go test -v ./...
  - overalls -project=github.com/QubitProducts/bamboo -covermode=count -debug -ignore=Godeps,webapp,builder,.git,vendor
  - goveralls -coverprofile=./overalls.coverprofile -service=travis-ci

notifications:
  email: false
