language: go

go:
  - 1.3

install:
  # WORKING DIR
  # $HOME/gopath/src/github.com/QubitProducts/bamboo
  - export PATH=$PATH:$HOME/gopath/bin

  # Install build dependencies
  - go get bitbucket.org/tebeka/go2xunit
  - go get -t github.com/smartystreets/goconvey
  - go get -v -u github.com/tools/godep

  # Restore project dependencies
  - godep restore

  # Travis auto execute go test
  #  - go test -v ./...

notifications:
  email: false
